import {createApp} from '../server/index.mjs';
import {chromium} from 'playwright';
import {mkdir,mkdtemp,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import assert from 'node:assert/strict';
const root=join(import.meta.dirname,'..');await mkdir(join(root,'work'),{recursive:true});await mkdir(join(root,'design/canonical'),{recursive:true});
const runtime=await createApp({mode:'development',dataDir:await mkdtemp(join(root,'work/canonical-qa-')),port:4322});const server=runtime.app.listen(4322,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const browser=await chromium.launch({headless:true,channel:"chrome"});const context=await browser.newContext({viewport:{width:1672,height:941}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:4322/');await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:join(root,'design/canonical/landing-desktop.png')});assert.equal(await page.locator('h1').innerText(),'Give Astra a place to work.');
 await page.getByRole('link',{name:'Get started',exact:true}).first().click();await page.screenshot({path:join(root,'design/canonical/early-access-desktop.png')});await page.locator('[name=email]').fill('preview@example.test');await page.locator('[name=size]').selectOption('Just me');await page.getByRole('button',{name:'Save early-access interest'}).click();assert.equal(await page.getByRole('heading',{name:'Your interest is saved on this device.'}).count(),1);await page.reload();assert.equal(await page.getByRole('heading',{name:'Your interest is saved on this device.'}).count(),1);await page.getByRole('button',{name:'Remove my saved entry'}).click();
 await page.goto('http://127.0.0.1:4322/workspace');await page.waitForTimeout(250);await page.screenshot({path:join(root,'design/canonical/workspace-desktop.png')});assert.equal(await page.locator('.inspector').count(),0);await page.getByRole('button',{name:'Show panel',exact:true}).click();assert.equal(await page.locator('.inspector').count(),1);assert.equal(await page.locator('.inspector .tabs').count(),0);await page.getByRole('button',{name:'Show tabs',exact:true}).click();assert.equal(await page.locator('.inspector .tabs').count(),1);await page.screenshot({path:join(root,'design/canonical/workspace-inspector-desktop.png')});
 for(const route of ['projects','runs','artifacts','skills','workflows','integrations','settings']){await page.goto('http://127.0.0.1:4322/workspace/'+route);assert.equal((await page.locator('h1').first().innerText()).toLowerCase(),route)}
 await page.goto('http://127.0.0.1:4322/#Skills');await page.waitForURL('**/workspace/skills');

 await page.goto('http://127.0.0.1:4322/workspace');await page.getByRole('button',{name:'Create a new project'}).click();await page.getByRole('button',{name:'Open development workspace',exact:true}).click();await page.getByRole('button',{name:'Create a new project'}).click();await page.getByLabel('Project name').fill('Canonical UI acceptance');await page.getByRole('button',{name:'Create project',exact:true}).click();await page.getByRole('button',{name:'Projects',exact:true}).click();await page.getByRole('button',{name:'Inspect project',exact:true}).click();await page.getByLabel('Project goal').fill('Verify the canonical interface');await page.getByLabel('Decisions and working notes').fill('Use only simulator execution');await page.getByRole('button',{name:'Save project context'}).click();await page.waitForResponse(r=>r.url().includes('/api/state'));assert.equal(runtime.store.all('projects')[0].goal,'Verify the canonical interface');await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByLabel('Task prompt').fill('Produce a local acceptance artifact');await page.getByRole('button',{name:'Run task',exact:true}).click();await page.getByRole('button',{name:/Show requests/}).click();await page.getByRole('button',{name:'Approve once'}).click();await page.getByRole('link',{name:/development-result.md/}).first().waitFor();await page.getByRole('button',{name:'Save layout template',exact:true}).click();await page.getByRole('status').filter({hasText:'Layout template saved'}).waitFor();assert.equal(runtime.store.all('workspace-templates').length,1);assert.ok(runtime.store.all('workspace-layouts')[0].panels.includes('artifacts'));await page.getByRole('tab',{name:'Artifacts',exact:true}).click();await page.screenshot({path:join(root,'design/polish/composed-workspace.png')});await page.getByRole('button',{name:'Artifacts',exact:true}).click();await page.getByRole('button',{name:/development-result.md/}).click();await page.getByRole('link',{name:'Download artifact'}).waitFor();
 await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByText('Create a runtime agent',{exact:true}).click();await page.getByLabel('Agent name',{exact:true}).fill('Canonical reviewer');await page.getByLabel('Agent instructions',{exact:true}).fill('Review the supplied context.');await page.getByRole('button',{name:'Create agent',exact:true}).click();await page.getByLabel('Step 1 agent').selectOption({label:'Canonical reviewer'});await page.getByLabel('Step 1 task').fill('Review this project');await page.getByRole('button',{name:'Save reusable template'}).click();await page.getByRole('button',{name:'Load Review and deliver'}).waitFor();await page.reload();await page.getByRole('button',{name:'Load Review and deliver'}).click();assert.equal(await page.getByLabel('Step 1 task').inputValue(),'Review this project');
 await page.goto('http://127.0.0.1:4322/');await page.getByRole('button',{name:'Use light theme'}).click();assert.equal(await page.evaluate(()=>getComputedStyle(document.body).backgroundColor),'rgb(246, 248, 246)');await page.screenshot({path:join(root,'design/canonical/landing-light.png')});await page.getByRole('button',{name:'Use dark theme'}).click();
 await page.goto('http://127.0.0.1:4322/workspace');await page.getByRole('button',{name:'Use light theme'}).click();await page.screenshot({path:join(root,'design/canonical/workspace-light.png')});await page.getByRole('button',{name:'Use dark theme'}).click();
 await page.setViewportSize({width:390,height:844});for(const route of ['/','/early-access','/workspace']){await page.goto('http://127.0.0.1:4322'+route);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Overflow '+route);await page.screenshot({path:join(root,'design/canonical/'+(route==='/'?'landing':route.slice(1))+'-mobile.png')})}
 await page.getByRole('button',{name:'Show panel',exact:true}).click();await page.getByRole('button',{name:'Close inspector'}).click();assert.equal(await page.locator('.inspector').count(),0);
 assert.deepEqual(errors,[]);console.log('Canonical routes, local form persistence/removal, independent panels, theme, legacy navigation, desktop/mobile overflow: passed.');
}finally{await browser.close();await new Promise(r=>server.close(r));runtime.store.close()}

