from pathlib import Path
import re,json,shutil,hashlib
root=Path.cwd();pack=root/'astra-brand-pack';source=Path(r'C:\Users\mrlyd\.codex\attachments\4eb6ba40-a91f-470f-9eda-3913c03010c9\pasted-text.txt');spec=source.read_text(encoding='utf-8');sections={int(m.group(1)):m.group(0) for m in re.finditer(r'^# (\d+) — .*?(?=^# \d+ — |\Z)',spec,re.M|re.S)}
def write(name,content):
 p=pack/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(content,encoding='utf-8')
def js(name,obj):write(name,json.dumps(obj,indent=2)+'\n')
write('00-START-HERE/canonical-source-v1.2.md',spec)
write('00-START-HERE/README.md','# Astra Workspace canonical brand pack\n\nVersion 1.2.0. The supplied v1.2 breakdown and four reference images supersede the cyan/violet v1.0 ZIP. This package preserves the supplied source verbatim, separates canonical requirements from implementation evidence, and supplies reusable vector/raster assets and tokens.\n\nStart with the source document, then 14-HANDOFF/acceptance-checklist.md. The running product lives one directory above this pack. Public pages: / and /early-access; application: /workspace. Development uses no real keys.\n\nThe folded A SVG is a clean vector reconstruction from the supplied raster references; an original v1.2 vector master was not supplied. Do not mistake the preserved v1.0 prism for the active mark.\n')
write('00-START-HERE/VERSION.md','# Version 1.2.0\n\nCanonical specification: supplied v1.2. Implementation date: 2026-09-06. v1.0 is retained as legacy provenance only.\n')
archive=Path(r'D:\sophie\astra-workspace-brand-package-v1.0.zip');(pack/'00-START-HERE/legacy').mkdir(parents=True,exist_ok=True);shutil.copy2(archive,pack/'00-START-HERE/legacy'/archive.name)
refs=[('landing','4041dc16-1f3a-4aa8-809c-b6dcd7d990ef'),('signup','c82d4501-8622-4f38-b6c8-d34281a29682'),('workspace','f5947a83-5ddb-42b1-b98e-bdfc55a752a5'),('blueprint','82483243-d793-4e08-9be6-545aa5d97311')]
for name,id in refs:
 folder=pack/'10-MOCKUPS'/name;folder.mkdir(parents=True,exist_ok=True);shutil.copy2(Path(r'C:\Users\mrlyd\AppData\Local\Temp')/('codex-clipboard-'+id+'.png'),folder/'supplied-reference.png')
files={'01-BRAND-CORE/positioning.md':[1,50],'01-BRAND-CORE/purpose.md':[1,3],'01-BRAND-CORE/messaging.md':[3,49],'01-BRAND-CORE/voice-tone.md':[2],'02-VISUAL-IDENTITY/visual-language.md':[16,17,18,19],'02-VISUAL-IDENTITY/imagery.md':[20,21],'02-VISUAL-IDENTITY/environmental-graphics.md':[9,20,21],'04-LOGO/usage-guide.md':[10,11,12,13],'05-TYPOGRAPHY/typography.md':[14],'05-TYPOGRAPHY/hierarchy.md':[15],'07-UI-CANONICALS/shell.md':[24],'07-UI-CANONICALS/runtime-bar.md':[25],'07-UI-CANONICALS/navigation.md':[23],'07-UI-CANONICALS/composer.md':[26],'07-UI-CANONICALS/modules.md':[27,28,29,30,31,32],'08-PRODUCT-ARCHITECTURE/project-model.md':[27],'08-PRODUCT-ARCHITECTURE/run-model.md':[28],'08-PRODUCT-ARCHITECTURE/artifacts-skills-workflows.md':[29,30,31],'11-COMPONENT-SYSTEM/controls.md':[17,18,19,22],'11-COMPONENT-SYSTEM/navigation.md':[23],'11-COMPONENT-SYSTEM/workspace.md':[24,25,26],'11-COMPONENT-SYSTEM/states.md':[8]}
for path,ids in files.items():write(path,'<!-- Canonical requirements extracted verbatim from the user-supplied v1.2 source. Not a claim that every future capability is implemented. -->\n\n'+'\n\n'.join(sections.get(i,'') for i in ids))
# Route remaining source sections to the corresponding topic without rewriting their requirements.
for name,pattern in [('02-VISUAL-IDENTITY/motion.md','Motion'),('07-UI-CANONICALS/inspector.md','Inspector'),('09-PAGE-BLUEPRINTS/landing.md','Landing'),('09-PAGE-BLUEPRINTS/early-access.md','Early|Signup'),('09-PAGE-BLUEPRINTS/workspace.md','Home'),('09-PAGE-BLUEPRINTS/authenticated-pages.md','Shell'),('12-MARKETING/SEO.md','SEO'),('13-AI-PROMPTS/frontend-canonical.md','Frontend|Prompt')]:
 matches=[v for v in sections.values() if re.search(pattern,v.splitlines()[0],re.I)];write(name,'\n\n'.join(matches) if matches else '# '+Path(name).stem+'\n\nApply the canonical source in 00-START-HERE. Preserve the supplied layouts, truthful feature states, accessible controls and local development boundaries.\n')
write('08-PRODUCT-ARCHITECTURE/information-architecture.md','# Information architecture\n\nAstra owns projects, runs, history, artifacts, approvals, skills activation and workflows. Execution adapters are replaceable. Codex app-server is one backend; Responses API is independent.\n\nConnect → Configure → Create → Run → Observe → Refine → Ship.\n\nModels are not accounts. Skills are canonical definitions, not automatically trusted runtime code. Discovery never enables execution. Local activation binds a qualified content hash to a supported runtime.\n')
write('08-PRODUCT-ARCHITECTURE/routes.md','# Routes\n\n| Route | Purpose |\n|---|---|\n| / | Public landing |\n| /early-access, /signup | Local early-access interest preview |\n| /workspace | Task composer and conversation |\n'+''.join('| /workspace/'+x.lower()+' | '+x+' |\n' for x in ['Projects','Runs','Artifacts','Skills','Workflows','Integrations','Settings'])+'\nKnown legacy hashes migrate to the matching workspace path. Browser back/forward and direct links resolve. Unknown public routes render a recovery page.\n')
write('12-MARKETING/messaging-hierarchy.md','# Messaging hierarchy\n\nAI Workspace / AI Agent Platform / Multi-Model AI Control Plane.\n\nGive Astra a place to work. Turn ideas into real work. Connect models, run tasks, retain artifacts and inspect execution. Mention collaboration, deployment endpoints and richer automation as future capabilities until verified.\n')
write('12-MARKETING/feature-copy.md','# Feature copy\n\nProjects — Organize work, ideas, and outcomes in one place.\nRuns — Give Astra a goal. Follow every execution.\nArtifacts — Keep, explore, and iterate on every output.\nIntegrations — Connect models, tools, and skills to fit your work.\n\nDo not publish enterprise certification, training-policy, pricing, team-account or provider-connectivity claims without evidence.\n')
write('12-MARKETING/social-copy.md','# Social copy\n\nGive Astra a place to work. A persistent AI workspace for projects, runs, artifacts, skills and workflows. Explore the local development preview.\n\nDo not say publicly available SaaS or live provider execution when sharing a simulator build.\n')
for name,prompt in [('image-generation','Preserve the supplied angular folded green A, obsidian and graphite surfaces, restrained orbital curves, and clear neutral typography. Do not introduce cyan, violet, neon, extra symbols or new branding.'),('landing-generation','Follow the supplied landing reference. Use the exact primary tagline. Keep navigation, hero, product preview, capabilities, how it works, trust, CTA and footer. Make text and controls native HTML. Replace unsupported claims with accurate product states.'),('workspace-generation','Preserve the desktop runtime bar, collapsible eight-item navigation, main workspace, composer and contextual inspector. Home panel and tabs are hidden until explicitly shown. Use Geist, outlined controls, silver hover, canonical green, persistent real state and no development secrets.')]:write('13-AI-PROMPTS/'+name+'.md','# '+name+'\n\n'+prompt+'\n')
dark={'canvas':'#0A0B0C','obsidian':'#0E1010','graphite':'#141616','charcoal':'#1C1F1E','elevated':'#232626','structuralLine':'#4F5151','text':'#F3F6F3','secondary':'#C8D0C8','muted':'#9DA89D','disabled':'#6E766E'}
light={'canvas':'#F6F8F6','surface':'#FFFFFF','secondarySurface':'#EEF3EE','border':'#D7DDD7','text':'#141616','secondaryText':'#5F6760','accent':'#407040'}
green={'primary':'#60B050','highlight':'#70C060','muted':'#407040','deep':'#305030'}
tokens={'version':'1.2.0','color':{'green':green,'dark':dark,'light':light},'radius':{'small':10,'medium':14,'large':18,'shell':24},'font':{'ui':'Geist, Inter, sans-serif','data':'IBM Plex Mono, monospace','code':'JetBrains Mono, monospace'},'border':{'B0':'none','B1':'1px solid #4F515140','B2':'1px solid #4F515166','B3':'1px solid #9DA89D88','B4':'1px solid #60B050'},'spacing':[4,8,12,16,20,24,32,40,48,64]}
js('03-COLOR/canonical-palette.json',{'green':green,'dark':dark,'light':light});js('03-COLOR/extracted-palette.json',{'method':'Exact hex values specified in supplied v1.2; not an inferred raster sampling',**green});js('03-COLOR/dark-mode.json',dark);js('03-COLOR/light-mode.json',light);js('06-DESIGN-TOKENS/tokens.json',tokens)
write('06-DESIGN-TOKENS/tokens.ts','export const astraTokens = '+json.dumps(tokens,indent=2)+' as const;\n')
write('06-DESIGN-TOKENS/tailwind.tokens.ts',"import {astraTokens} from './tokens';\nexport default {theme:{extend:{colors:{astra:astraTokens.color.green},borderRadius:{sm:'10px',md:'14px',lg:'18px',xl:'24px'},fontFamily:{sans:['Geist','Inter','sans-serif'],mono:['JetBrains Mono','monospace']}}}};\n")
css=(root/'src/canonical.css').read_text();rules='\n'.join(line for line in css.splitlines() if line.startswith(':root'))+'\n';write('06-DESIGN-TOKENS/tokens.css',rules)
for dirname in ['svg','png','monochrome','app-icons']:(pack/'04-LOGO'/dirname).mkdir(parents=True,exist_ok=True)
svg=(root/'public/astra-folded-a.svg').read_text();write('04-LOGO/svg/astra-symbol.svg',svg)
for name,color in [('green','#60B050'),('white','#FFFFFF'),('black','#000000')]:
 mono=re.sub(r'<defs>.*?</defs>','',svg,flags=re.S);mono=re.sub(r'fill="(?:url\([^)]+\)|#[A-Fa-f0-9]+)"','fill="'+color+'"',mono);mono=re.sub(r' fill-opacity="[^"]+"','',mono);write('04-LOGO/monochrome/astra-'+name+'.svg',mono)
lockup=svg.replace('viewBox="0 0 100 100"','viewBox="0 0 540 100"').replace('</svg>','<text x="112" y="64" font-family="Geist, Inter, sans-serif" font-size="44" fill="#F3F6F3" letter-spacing="-1">Astra Workspace</text></svg>');write('04-LOGO/svg/astra-horizontal-dark.svg',lockup);write('04-LOGO/svg/astra-horizontal-light.svg',lockup.replace('#F3F6F3','#141616'))
for font in ['geist','ibm-plex-mono','jetbrains-mono']:
 lic=root/'node_modules/@fontsource'/font/'LICENSE';target=pack/'05-TYPOGRAPHY/licenses';target.mkdir(exist_ok=True)
 if lic.exists():shutil.copy2(lic,target/(font+'.txt'))
manifest={'name':'Astra Workspace','version':'1.2.0','canonicalSource':'canonical-source-v1.2.md','sourceSHA256':hashlib.sha256(source.read_bytes()).hexdigest(),'legacyZipSHA256':hashlib.sha256(archive.read_bytes()).hexdigest(),'logoProvenance':'Vector reconstruction from supplied v1.2 raster references; legacy vector rejected as superseded','referenceImages':[x[0] for x in refs],'runtimeMode':'development','realSecretsUsed':False}
js('00-START-HERE/BRAND-MANIFEST.json',manifest)
write('14-HANDOFF/DO-NOT-DRIFT.md','# Do not drift\n\nPreserve the exact tagline, geometric green mark, obsidian/graphite palette, desktop operational shell and canonical navigation. The supplied v1.2 source takes priority over v1.0. Do not add real secrets in development. Do not turn discovery into trust, Codex into the control plane, or simulator completion into a live-provider claim.\n')
write('14-HANDOFF/FRONTEND-HANDOFF.md','# Frontend handoff\n\nSite.jsx composes public pages. App.jsx owns workspace state. routes.js resolves canonical paths and legacy hashes. canonical.css applies v1.2 over preserved base modules. ThemeControl persists the selected theme. Fonts are bundled locally, with licenses in 05-TYPOGRAPHY.\n\nUse node scripts/npm.mjs install for this Windows environment, then node scripts/development.mjs. Build with node node_modules/vite/bin/vite.js build. Browser checks: node scripts/canonical-qa.mjs. Runtime checks: node --test test/*.test.mjs.\n\nThe early-access form deliberately stores a removable local interest record; it creates no hosted account and sends no email. Public preview controls are links to the actual workspace, not fake model selectors.\n')
write('14-HANDOFF/DESIGN-HANDOFF.md','# Design handoff\n\nThe four untouched references are in 10-MOCKUPS. Compare them against design/canonical in the parent project. The SVG mark is reconstructed from the reference silhouette, not extracted from an original vector master. Product buttons remain outlined glass; green filled gradients are reserved for public conversion controls.\n\nUse 14-HANDOFF/fidelity-ledger.md for documented copy and implementation differences.\n')
write('14-HANDOFF/AI-HANDOFF.md','# AI handoff\n\nRead the canonical source and acceptance checklist before extending the product. Astra owns orchestration, persistence, runtime bindings and approvals. Responses and Codex are independent execution adapters. Skill Hub is read-only upstream; only qualified native skills become executable. Development must remain a deterministic, network-free model simulator with real local orchestration.\n\nFuture expansion includes team identity, collaboration, hosted waitlist, OAuth connectors, arbitrary DAG workflow execution and deployment endpoints. Do not advertise these as shipped.\n')
print('Canonical source, references, tokens, logo family and handoff package written:',pack)
