import WorkspaceSurfaces from './WorkspaceSurfaces';
import ResourceInspector from './ResourceInspector';
import {workspaceView,workspacePath} from './routes';import ThemeControl from './ThemeControl';
import React,{useState,useEffect,useRef}from'react';import{api}from'./api';import{Logo,Icon,Button,Panel,Empty,Status,number,time}from'./ui';import{Management,ProviderForm,ProjectForm,Unlock}from'./Management';import{Inspector}from'./Inspector';import {Skills} from './Skills';import {Workflows} from './Workflows';
const initial={projects:[],conversations:[],runs:[],messages:[],files:[],artifacts:[],providers:[],connectors:[],agents:[],approvals:[],settings:{model:'gpt-6-astra',reasoning:'high',backend:'responses',providerId:''}};
export default function App(){
 const [state,setState]=useState(initial),[auth,setAuth]=useState(null),[view,setViewState]=useState(workspaceView),[projectId,setProjectId]=useState(localStorage.getItem('astra-project')||''),[conversationId,setConversationId]=useState(localStorage.getItem('astra-conversation')||''),[selectedRun,setSelectedRun]=useState(''),[modal,setModal]=useState(''),[error,setError]=useState(''),[prompt,setPrompt]=useState(()=>localStorage.getItem('astra-task-draft')||''),[fileIds,setFileIds]=useState([]),[busy,setBusy]=useState(false),[mobile,setMobile]=useState(window.innerWidth>900),[showPanel,setShowPanel]=useState(false),[showTabs,setShowTabs]=useState(false),[agentId,setAgentId]=useState(''),[showHistory,setShowHistory]=useState(false),[taskType,setTaskType]=useState('General task'),[templates,setTemplates]=useState(false),[contextOpen,setContextOpen]=useState(false),[resource,setResource]=useState(null);
 const setView=v=>{setResource(null);setViewState(v);history.pushState({},'',workspacePath(v))};
 useEffect(()=>{const change=()=>{setResource(null);setViewState(workspaceView())};window.addEventListener('popstate',change);window.addEventListener('hashchange',change);return()=>{window.removeEventListener('popstate',change);window.removeEventListener('hashchange',change)}},[]);
 useEffect(()=>{const expired=()=>{setAuth(a=>({...a,unlocked:false}));setState(initial);setModal('unlock');setError('Session expired. Reopen your workspace to continue.');};window.addEventListener('astra-session-expired',expired);return()=>window.removeEventListener('astra-session-expired',expired)},[]);
 useEffect(()=>{localStorage.setItem('astra-task-draft',prompt)},[prompt]);
 const tail=useRef(),scroller=useRef(),following=useRef(true),upload=useRef();
 const refresh=async()=>{const data=await api('/state');setState(current=>document.activeElement?.getAttribute('aria-label')==='Model'?{...data,settings:{...data.settings,model:current.settings.model}}:data);return data};
 useEffect(()=>{api('/auth/status').then(setAuth).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!auth?.unlocked)return;refresh().catch(e=>setError(e.message));const id=setInterval(()=>refresh().catch(()=>{}),1500);return()=>clearInterval(id)},[auth?.unlocked]);
 useEffect(()=>{localStorage.setItem('astra-project',projectId);localStorage.setItem('astra-conversation',conversationId)},[projectId,conversationId]);
 const act=async fn=>{setError('');try{return await fn()}catch(e){setError(e.message);return null}};
 const project=state.projects.find(p=>p.id===projectId),conversation=state.conversations.find(c=>c.id===conversationId),runs=state.runs.filter(r=>r.conversationId===conversationId),run=state.runs.find(r=>r.id===selectedRun)||runs.at(-1),provider=state.providers.find(p=>p.id===state.settings.providerId);
 const messages=state.messages.filter(m=>m.conversationId===conversationId),visibleMessages=showHistory?messages:messages.slice(-8);const active=run&&['queued','running','awaiting_approval'].includes(run.status);
 useEffect(()=>{if(following.current)scroller.current?.scrollTo({top:scroller.current.scrollHeight,behavior:'smooth'})},[messages.length,run?.partial]);
 const saveSettings=patch=>{if(!auth?.unlocked){setModal('unlock');return Promise.resolve(null)}return act(async()=>{await api('/settings',{...state.settings,...patch},'PUT');return await refresh()})};
 const openConversation=c=>{setProjectId(c.projectId);setConversationId(c.id);setSelectedRun('');setView('Home');if(window.innerWidth<901)setMobile(false)};
 const newConversation=id=>{setProjectId(id||projectId);setConversationId('');setSelectedRun('');setPrompt('');setFileIds([]);setView('Home');if(window.innerWidth<901)setMobile(false)};
 const submit=async e=>{e?.preventDefault();if(busy||!prompt.trim())return;if(!auth?.unlocked){setModal('unlock');return}if(!project){setModal('project');return}if(!provider){setModal('provider');return}setBusy(true);await act(async()=>{const r=await api('/runs',{prompt:taskType==='General task'?prompt:taskType+': '+prompt,projectId,conversationId:conversation?.id,providerId:provider.id,backend:state.settings.backend,model:state.settings.model,reasoning:state.settings.reasoning,fileIds,agentId});setConversationId(r.conversationId);setSelectedRun(r.id);setPrompt('');setFileIds([]);following.current=true;await refresh()});setBusy(false)};
 const addFiles=async files=>{if(!project){setModal('project');return}for(const f of files){if(f.size>200000){setError('Attach text or code files up to 200 KB.');continue}await act(async()=>{const saved=await api('/files',{projectId,name:f.name,content:await f.text()});setFileIds(ids=>[...ids,saved.id]);await refresh()})}};
 const pending=state.approvals.filter(a=>a.status==='pending');
 const navigate=x=>{setView(x);if(window.innerWidth<901)setMobile(false);if(!auth?.unlocked&&x!=='Home')setModal('unlock')};
 return <div className={'app-shell polished '+(mobile?'nav-open ':'nav-closed ')+((showPanel||showTabs)?'with-inspector':'without-inspector')}>
 <header className="topbar"><div className="brand"><button className="mobile-menu" aria-label={mobile?"Close navigation":"Open navigation"} aria-expanded={mobile} aria-controls="workspace-navigation" onClick={()=>setMobile(!mobile)}><Icon name="Menu"/></button><Logo/><strong>Astra Workspace</strong>{auth?.mode==='development'&&<span className="dev-badge">Development · simulated</span>}</div>
 <div className="global-controls"><label><Icon name="Globe"/><span>Provider:</span><select aria-label="Provider" value={state.settings.providerId||''} onChange={e=>e.target.value==='connect'?setModal('provider'):saveSettings({providerId:e.target.value})}><option value="">{auth?.mode==='development'?'Simulator':'Choose provider'}</option>{state.providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}<option value="connect">+ Connect provider</option></select></label>
 <label className="model-control"><span>Model:</span><input aria-label="Model" list="models" value={auth?.mode==='development'&&!auth?.unlocked?'astra-development':state.settings.model||''} onChange={e=>setState(s=>({...s,settings:{...s.settings,model:e.target.value}}))} onBlur={e=>saveSettings({model:e.target.value})}/><datalist id="models">{(provider?.models||[]).map(m=><option key={m} value={m}/>)}</datalist></label>
 <label><span>Reasoning:</span><select aria-label="Reasoning" value={state.settings.reasoning} onChange={e=>saveSettings({reasoning:e.target.value})}>{['low','medium','high','xhigh','max'].map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</select></label>
 <label><span>Backend:</span><select aria-label="Backend" value={state.settings.backend} onChange={e=>saveSettings({backend:e.target.value})}><option value="responses">{auth?.mode==='development'?'Simulator':'Responses API'}</option>{auth?.mode!=='development'&&<option value="codex">Codex local</option>}</select></label></div>
 <ThemeControl/><button className="lock-button" title={auth?.unlocked?'Lock workspace':'Unlock workspace'} aria-label="Lock workspace" onClick={()=>auth?.unlocked?act(async()=>{await api('/auth/lock',{});setAuth({...auth,unlocked:false});setState(initial)}):setModal('unlock')}><Icon name="Lock"/></button></header>
 <aside id="workspace-navigation" className={'sidebar '+(mobile?'open':'')}><nav>{['Home','Projects','Runs','Artifacts','Skills','Workflows','Integrations','Settings'].map(x=><button key={x} className={view===x?'selected':''} onClick={()=>navigate(x)} aria-current={view===x?'page':undefined}><Icon name={x} size={21}/>{x}</button>)}</nav><div className="recent-heading"><span>Recent</span><button aria-label="New project" onClick={()=>setModal('project')}><Icon name="Plus"/></button></div><div className="recent-list">{state.conversations.slice(-7).reverse().map(c=><button key={c.id} className={conversationId===c.id?'current':''} onClick={()=>openConversation(c)}><Icon name="MessageSquare"/><span>{c.title}<small>{state.projects.find(p=>p.id===c.projectId)?.name}</small></span></button>)}</div><div className="sidebar-foot"><Icon name="ShieldCheck"/><span>Local workspace<small>{auth?.mode==='development'?'No real credentials · local test data':auth?.unlocked?'Encrypted keys · persistent history':'Your keys stay on this device'}</small></span></div></aside>
 <main className="main"><img className="glass-overlay" src="/astra-glass-overlay.svg" alt=""/><div className="surface-tools"><Button aria-pressed={showPanel} onClick={()=>setShowPanel(!showPanel)}>{showPanel?'Hide panel':'Show panel'}</Button><Button aria-pressed={showTabs} onClick={()=>setShowTabs(!showTabs)}>{showTabs?'Hide tabs':'Show tabs'}</Button>{pending.length>0&&<Button onClick={()=>{const a=pending[0],r=state.runs.find(x=>x.id===a.runId);if(r){setProjectId(r.projectId);setConversationId(r.conversationId);setSelectedRun(r.id);setView('Home');}setShowPanel(true)}}>Show requests ({pending.length})</Button>}</div>{auth?.mode==='development'&&<div className="dev-notice" role="status">Development mode: no real keys, external model calls or charges. Runs use a deterministic simulator.</div>}{error&&<div className="error-banner" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><Icon name="X"/></button></div>}
 {view==='Home'?<>{project&&<div className="workspace-heading"><div><h1>{project?.name||'Astra workspace'}</h1><p>{project?.description||'Persistent AI workspace.'}</p></div>{project&&<Button icon="Plus" onClick={()=>newConversation()}>New conversation</Button>}</div>}
 <div className="conversation-scroll" ref={scroller} onScroll={()=>{const e=scroller.current;following.current=e.scrollHeight-e.scrollTop-e.clientHeight<100}}>
 {!messages.length?<div className="welcome"><p className="eyebrow">Astra Workspace</p><h2>Turn ideas into real work.</h2><p>Describe a task, add context, and let Astra plan, run, and deliver.</p><div className="home-actions">{[['Projects','Create a new project','Start with a clean workspace'],['Workflows','Run a workflow','Automate complex tasks'],['Integrations','Connect an integration','Bring in your tools and data'],['Skills','Explore skills','Extend with specialized skills']].map(([v,title,description])=><button key={v} onClick={()=>v==='Projects'?setModal(auth?.unlocked?'project':'unlock'):navigate(v)}><Icon name={v} size={24}/><span>{title}<small>{description}</small></span></button>)}</div></div>:<div className="messages">{messages.length>8&&<button className="history-toggle" onClick={()=>setShowHistory(!showHistory)}>{showHistory?'Show recent messages':'Show earlier messages ('+(messages.length-8)+')'}</button>}{visibleMessages.map(m=><article className={'message '+m.role} key={m.id}>{m.role==='assistant'?<Logo/>:<div className="avatar">You</div>}<div className="message-body"><div className="message-meta"><strong>{m.role==='assistant'?'Astra':'You'}</strong><time>{time(m.createdAt)}</time></div><div className="message-text">{m.content}</div></div></article>)}{run?.partial&&<article className="message"><Logo/><div className="message-body"><div className="message-meta"><strong>Astra</strong><Status value="running"/></div><div className="message-text">{run.partial}</div></div></article>}{active&&<div className="live-row"><span className="pulse"/>{run.status==='awaiting_approval'?'Your approval is needed in the Run panel.':'Astra is working…'}</div>}{run?.error&&<div className="run-error"><Status value={run.status}/><p>{run.error}</p></div>}{state.artifacts.filter(a=>a.runId===run?.id).map(a=><a className="artifact-inline" href={'/api/artifacts/'+a.id} key={a.id}><Icon name="Artifacts"/><span>{a.name}<small>{number(a.size)} bytes</small></span><Icon name="Download"/></a>)}</div>}<WorkspaceSurfaces state={state} run={run} act={act} refresh={refresh}/><div ref={tail}/></div>
 <form className="composer" onSubmit={submit}><div className="composer-topline"><select aria-label="Task type" value={taskType} onChange={e=>setTaskType(e.target.value)}>{['General task','Coding task','Research task','Analysis task'].map(t=><option key={t}>{t}</option>)}</select><div><Button type="button" aria-expanded={templates} onClick={()=>setTemplates(!templates)}>Templates</Button><Button type="button" onClick={()=>navigate('Settings')}>Advanced</Button></div></div>{templates&&<div className="template-options">{['Summarize the attached files and save a report.','Review this project and propose the next implementation steps.','Create a task plan with clear acceptance criteria.'].map(t=><button type="button" key={t} onClick={()=>{setPrompt(t);setTemplates(false)}}>{t}</button>)}</div>}<textarea aria-label="Task prompt" placeholder="Describe what you want Astra to do..." value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();submit()}}}/>
 {contextOpen&&<div className="composer-context"><select aria-label="Task project context" value={projectId} onChange={e=>{setProjectId(e.target.value);setConversationId('');setFileIds([])}}><option value="">Select project</option>{state.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><span className="hint">{project?'Project description and selected files accompany this task.':'Select a project to keep task context and results together.'}</span></div>}{fileIds.length>0&&<div className="attached">{fileIds.map(id=><button type="button" key={id} onClick={()=>setFileIds(ids=>ids.filter(x=>x!==id))}>{state.files.find(f=>f.id===id)?.name}<Icon name="X" size={12}/></button>)}</div>}
 <div className="composer-controls"><div><Button type="button" icon="Paperclip" onClick={()=>!auth?.unlocked?setModal('unlock'):!project?setModal('project'):upload.current.click()}>Add files</Button><Button type="button" icon="Database" aria-expanded={contextOpen} onClick={()=>setContextOpen(!contextOpen)}>Add context</Button><input ref={upload} type="file" hidden multiple accept=".txt,.md,.csv,.json,.js,.jsx,.ts,.tsx,.py,.html,.css,.xml,.yaml,.yml,.sql,.log" onChange={e=>{addFiles([...e.target.files]);e.target.value=''}}/><button type="button" className={'button '+(state.settings.webSearch?'enabled':'')} aria-pressed={!!state.settings.webSearch} onClick={()=>saveSettings({webSearch:!state.settings.webSearch})}><Icon name="Globe"/>Web search</button>{state.agents.length>0&&<select aria-label="Agent" value={agentId} onChange={e=>setAgentId(e.target.value)}><option value="">Astra</option>{state.agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>}</div><Button primary icon="Play" type="submit" disabled={busy||active||!prompt.trim()}>{busy?'Starting…':'Run task'}</Button></div></form></>:view==='Skills'?<Skills onInspect={r=>setResource(r?{...r,kind:'skill'}:null)} state={state} projectId={projectId} refresh={refresh} act={act} onRun={r=>{setConversationId(r.conversationId);setSelectedRun(r.id);setView('Home')}}/>:view==='Workflows'?<Workflows onInspect={r=>{setResource({...r,kind:'workflow'});setShowPanel(true)}} state={state} projectId={projectId} refresh={refresh} act={act} selectRun={r=>{setProjectId(r.projectId);setConversationId(r.conversationId);setSelectedRun(r.id);setView('Home');setShowPanel(true)}}/>:<Management onInspect={r=>{setResource(r);setShowPanel(true)}} view={view} state={state} refresh={refresh} act={act} setModal={setModal} newConversation={newConversation} openConversation={openConversation} selectRun={r=>{setProjectId(r.projectId);setConversationId(r.conversationId);setSelectedRun(r.id);setView('Home')}} saveSettings={saveSettings}/>}
 </main>{(showPanel||showTabs)&&(view!=='Home'?<ResourceInspector onClose={()=>{setShowPanel(false);setShowTabs(false)}} view={view} resource={resource} state={state} showPanel={showPanel} showTabs={showTabs} refresh={refresh} act={act}/>:<Inspector onClose={()=>{setShowPanel(false);setShowTabs(false)}} showPanel={showPanel} showTabs={showTabs} state={state} run={run} project={project} provider={run?state.providers.find(p=>p.id===run.providerId):provider} act={act} refresh={refresh}/>)}
 {(modal==='unlock'||(auth&&!auth.unlocked&&modal))&&<Unlock auth={auth} onClose={()=>setModal('')} onSuccess={async()=>{setAuth({...auth,configured:true,unlocked:true});setModal('');await refresh()}}/>}
 {modal==='provider'&&auth?.unlocked&&<ProviderForm development={auth?.mode==='development'} onClose={()=>setModal('')} onSave={async data=>{await api('/providers',data);await refresh();setModal('')}}/>}
 {modal==='project'&&auth?.unlocked&&<ProjectForm onClose={()=>setModal('')} onSave={async data=>{const p=await api('/projects',data);await refresh();newConversation(p.id);setModal('')}}/>}
 </div>
}
