import QuestionForm from './QuestionForm';
import React,{useState,useEffect}from'react';import{api}from'./api';import{Panel,Empty,Icon,Button,Status,number,time}from'./ui';
export function Inspector({state,run,project,provider,act,refresh,showPanel=true,showTabs=true,onClose}){
 const[tab,setTab]=useState('Run'),[events,setEvents]=useState([]),[expanded,setExpanded]=useState(false),[deciding,setDeciding]=useState(false);
 useEffect(()=>{if(!run){setEvents([]);return}let alive=true;const load=()=>api('/runs/'+run.id+'/events').then(e=>alive&&setEvents(e)).catch(()=>{});load();const id=setInterval(load,1500);return()=>{alive=false;clearInterval(id)}},[run?.id]);
 const approvals=state.approvals.filter(a=>a.runId===run?.id&&a.status==='pending'),usage=run?.usage||{},total=(usage.input_tokens||0)+(usage.output_tokens||0),active=run&&['queued','running','awaiting_approval'].includes(run.status);
 const decide=async(id,approved)=>{if(deciding)return;setDeciding(true);await act(async()=>{await api('/approvals/'+id,{approved});await refresh()});setDeciding(false)};
 const displayEvents=expanded?events:events.slice(-8);
 return <aside className="inspector"><button className="inspector-close" aria-label="Close inspector" onClick={onClose}><Icon name="X"/></button>{showTabs&&<div className="tabs">{['Run','Context','Files','Tools'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}{t==='Run'&&approvals.length>0&&<span className="count">{approvals.length}</span>}</button>)}</div>}{showPanel&&<div className="inspector-body">
 {tab==='Run'&&<>{run?<Panel title={<Status value={run.status}/>}><p className="muted">{active?'Executing task…':run.error||'Execution '+run.status+'.'}</p><div className="panel-actions">{active?<Button icon="Square" onClick={()=>act(async()=>{await api('/runs/'+run.id+'/cancel',{});await refresh()})}>Cancel</Button>:<a href={'/api/runs/'+run.id+'/export'} className="button"><Icon name="Download"/>Audit record</a>}</div></Panel>:<Panel><Empty title="Ready when you are">Connect a provider and start your first task.</Empty></Panel>}
 {approvals.map(a=>a.type==='user_input'?<QuestionForm key={a.id} request={a} refresh={refresh}/>:<Panel key={a.id} title={<span className="approval-title"><Icon name="ShieldCheck"/>Approval required</span>}><strong>{a.type.replaceAll('_',' ')}</strong><pre className="approval-preview">{JSON.stringify(a.data,null,2)}</pre><div className="panel-actions"><Button disabled={deciding} onClick={()=>decide(a.id,false)}>Deny</Button><Button primary disabled={deciding} onClick={()=>decide(a.id,true)}>Approve once</Button></div></Panel>)}
 {run&&<Panel title="Execution details"><dl><dt>Run ID</dt><dd className="resource-id">{run.id}</dd><dt>Created</dt><dd>{new Date(run.createdAt).toLocaleString()}</dd><dt>Duration</dt><dd>{run.startedAt?Math.max(0,Math.round(((run.endedAt?Date.parse(run.endedAt):Date.now())-Date.parse(run.startedAt))/1000))+' seconds':'Not started'}</dd><dt>Reasoning</dt><dd>{run.reasoning}</dd><dt>Attachments</dt><dd>{run.contextSnapshot?.fileIds?.length||0}</dd></dl></Panel>}<Panel title="Usage">{!total?<><p>No usage yet</p><p className="muted">Run a task to see token usage.</p></>:<><div className="usage-total">{number(total)} <span>tokens</span></div><div className="meter"><i style={{width:Math.min(100,total/(run.contextLimit||32000)*100)+'%'}}/></div><div className="usage-labels"><span>Input <b>{number(usage.input_tokens)}</b></span><span>Output <b>{number(usage.output_tokens)}</b></span></div><p className="muted">{run.cost==null?'Cost rates not configured':'Estimated token cost: $'+run.cost.toFixed(4)}</p></>}</Panel>
 <Panel title="Model & Provider"><p className="provider-label"><Icon name="Link" size={24}/>{provider?.name||(run?'Provider unavailable':'Not connected')}</p><p className="muted">{provider?<>{run?.model||state.settings.model}<br/>{run?.backend||state.settings.backend} · {run?.reasoning||state.settings.reasoning} reasoning</>:'Connect a provider to get started.'}</p></Panel>
 <Panel title="Run timeline" action={events.length>8&&<button className="text-button" onClick={()=>setExpanded(!expanded)}>{expanded?'Recent':'View all'}</button>}>{!events.length?<><p className="timeline-empty"><Icon name="Clock"/>Your next run starts here.</p><p className="muted">Timeline will appear once you run a task.</p></>:<div className="timeline">{displayEvents.map(e=><details key={e.id}><summary><span className="timeline-dot"/><span>{e.type.replaceAll('_',' ').replaceAll('/',' / ')}</span><time>{time(e.createdAt)}</time></summary><pre>{JSON.stringify(e.data,null,2)}</pre></details>)}</div>}</Panel></>}
 {tab==='Context'&&<><Panel title="Working context"><p>{project?.name||'No project selected'}</p><p className="muted">{project?.description||'Project descriptions help organize your work.'}</p><dl><dt>Context budget</dt><dd>{number(run?.contextLimit||state.settings.contextLimit)} tokens</dd><dt>Reasoning</dt><dd>{run?.reasoning||state.settings.reasoning}</dd><dt>Persistence</dt><dd>Local SQLite</dd></dl><p className="hint">Previous conversation messages are included in Responses runs. Codex resumes its backend thread.</p></Panel><Panel title="Project directory"><code className="path">{project?.path||'Create a project to allocate a directory.'}</code></Panel></>}
 {tab==='Files'&&<><Panel title="Project files">{state.files.filter(f=>f.projectId===project?.id).map(f=><a className="file-row" key={f.id} href={'/api/files/'+f.id} target="_blank" rel="noreferrer"><Icon name="Artifacts"/><span>{f.name}<small>{number(f.size)} bytes</small></span></a>)}{!state.files.some(f=>f.projectId===project?.id)&&<p className="muted">Attach text or code files from the composer.</p>}</Panel><Panel title="Artifacts">{state.artifacts.filter(a=>a.projectId===project?.id).map(a=><a className="file-row" key={a.id} href={'/api/artifacts/'+a.id}><Icon name="Download"/>{a.name}</a>)}{!state.artifacts.some(a=>a.projectId===project?.id)&&<p className="muted">Generated artifacts appear here.</p>}</Panel></>}
 {tab==='Tools'&&<><Panel title="Tool availability"><dl><dt>Create artifact</dt><dd>Approval required</dd><dt>Web search</dt><dd>{state.settings.webSearch?'Enabled':'Disabled'}</dd><dt>Browser actions</dt><dd>{state.settings.browser?'Approval required':'Disabled'}</dd><dt>Code / terminal</dt><dd>Codex backend</dd><dt>MCP servers</dt><dd>{state.connectors.filter(c=>c.enabled).length} enabled</dd></dl></Panel><Panel title="Tool activity">{events.filter(e=>/tool_|provider_item|item\/completed/.test(e.type)).map(e=><details key={e.id}><summary>{e.data.name||e.data.type||e.type}</summary><pre>{JSON.stringify(e.data,null,2)}</pre></details>)}</Panel></>}
 </div>}</aside>
}
