import React,{useEffect,useRef,useState} from 'react';

export function useLandingMotion(){
 const [enabled,setEnabled]=useState(()=>!matchMedia('(prefers-reduced-motion: reduce)').matches);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setEnabled(!media.matches);media.addEventListener('change',sync);window.addEventListener('astra-motion-change',sync);return()=>{media.removeEventListener('change',sync);window.removeEventListener('astra-motion-change',sync)}},[]);
 return enabled;
}
function useVisible(ref){const[visible,setVisible]=useState(false);useEffect(()=>{const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting));observer.observe(ref.current);return()=>observer.disconnect()},[ref]);return visible}
const slogans=['Connect your models. Give Astra a goal. Keep every result in one workspace.','From the first idea to the final artifact. One continuous place to work.','Bring your tools, files, and context. Turn ambitious plans into tangible work.'];
export function HeroTypewriter(){const ref=useRef(),enabled=useLandingMotion(),visible=useVisible(ref);const[state,setState]=useState({index:0,count:slogans[0].length,deleting:false});
 useEffect(()=>{if(!enabled||!visible)return;let timer;const tick=()=>{if(document.hidden){timer=setTimeout(tick,300);return}setState(s=>s.deleting?(s.count>0?{...s,count:s.count-1}:{index:(s.index+1)%slogans.length,count:0,deleting:false}):(s.count<slogans[s.index].length?{...s,count:s.count+1}:{...s,deleting:true}));};const complete=state.count===slogans[state.index].length;timer=setTimeout(tick,complete&&!state.deleting?3600:state.deleting?17:38);return()=>clearTimeout(timer)},[state,enabled,visible]);
 return <p ref={ref} className="hero-typewriter"><span className="landing-sr-only">{slogans[0]}</span><span aria-hidden="true">{enabled?slogans[state.index].slice(0,state.count):slogans[0]}<i className={enabled?'type-caret':'type-caret still'}/></span></p>
}
const stages=[
 ['Connect','Your models, together.','Choose an execution provider for the work ahead.','Simulator · local development'],
 ['Configure','Set the scope.','Choose reasoning, context, and the boundaries Astra works within.','Reasoning · context · permissions'],
 ['Create','Start with an intention.','Describe the result you need and bring the relevant files.','Create a launch brief from my project notes.'],
 ['Run','Watch the work unfold.','Astra moves through the task with a visible execution history.','Plan → prepare → produce'],
 ['Observe','Every step, in view.','Inspect requests, review approvals, and explore the output.','Timeline · approvals · artifacts'],
 ['Refine','Keep the context.','Continue the conversation and improve the result in the same project.','Revise the brief with a clearer next step.'],
 ['Ship','Take the result forward.','Open the artifact, download it, and return whenever you need.','launch-brief.md · ready to review']
];
export function PipelineDemo(){const rail=useRef(),ref=useRef(),enabled=useLandingMotion(),visible=useVisible(ref),[step,setStep]=useState(0),[paused,setPaused]=useState(false);const playing=enabled&&visible&&!paused;
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>{if(!document.hidden)setStep(s=>(s+1)%stages.length)},4200);return()=>clearInterval(timer)},[playing,step]);
 useEffect(()=>{const node=rail.current,button=node.children[step];if(node.scrollWidth>node.clientWidth)node.scrollTo({left:button.offsetLeft-node.offsetLeft-(node.clientWidth-button.offsetWidth)/2,behavior:enabled?'smooth':'instant'})},[step,enabled]);
 const select=index=>{setStep(index);setPaused(true)};
 return <div ref={ref} className="pipeline-demo" data-playing={playing}><div className="pipeline-toolbar"><span>Workspace walkthrough <small>Illustrative demo</small></span><button type="button" disabled={!enabled} onClick={()=>setPaused(!paused)} aria-label={paused?'Play pipeline demonstration':'Pause pipeline demonstration'}>{paused?'Play':'Pause'}</button></div><div ref={rail} className="pipeline-stages" role="group" aria-label="Choose a workflow stage">{stages.map(([name],i)=><button type="button" key={name} aria-pressed={i===step} onClick={()=>select(i)}><span className="pipeline-node">{i<step?'✓':String(i+1).padStart(2,'0')}</span><span>{name}</span></button>)}</div><div className="pipeline-scene" key={step}><div className="pipeline-copy"><span className="pipeline-caption">{stages[step][0]}</span><h3>{stages[step][1]}</h3><p>{stages[step][2]}</p></div><div className="pipeline-output"><svg viewBox="0 0 360 100" fill="none" aria-hidden="true"><path d="M10 50H95C125 50 125 20 155 20H205C235 20 235 50 265 50H350M95 50C125 50 125 80 155 80H205C235 80 235 50 265 50"/><path className="pipeline-signal" d="M10 50H95C125 50 125 20 155 20H205C235 20 235 50 265 50H350"/>{[35,180,325].map((x,i)=><g key={x}><circle cx={x} cy={50} r="16"/><circle className="pipeline-core" cx={x} cy={50} r={i===step%3?6:3}/></g>)}</svg><span>{stages[step][3]}</span><div className="pipeline-progress"><i/></div></div></div><div className="pipeline-controls"><button type="button" onClick={()=>select((step+6)%7)} aria-label="Previous pipeline stage">← Previous</button><span>{step+1} / 7</span><button type="button" onClick={()=>select((step+1)%7)} aria-label="Next pipeline stage">Next →</button></div></div>
}
export function PreviewActivity(){const ref=useRef(),enabled=useLandingMotion(),visible=useVisible(ref),[step,setStep]=useState(0);useEffect(()=>{if(!enabled||!visible)return;const timer=setInterval(()=>{if(!document.hidden)setStep(s=>(s+1)%4)},3000);return()=>clearInterval(timer)},[enabled,visible]);return <div ref={ref} className="preview-activity" data-active={enabled} aria-label="Illustrative workspace activity"><span className="preview-demo-label">WORKSPACE DEMO</span><div className="preview-activity-line" key={step}><i/><span>{['Task received · preparing project context','Planning · organizing the next steps','Producing · drafting your launch brief','Artifact ready · launch-brief.md'][step]}</span></div><div className="preview-step-track">{['Context','Plan','Create','Artifact'].map((name,i)=><span className={i<=step?'lit':''} key={name}>{name}</span>)}</div></div>}
export function TrustArt({kind}){return <svg className="trust-art" viewBox="0 0 260 110" fill="none" aria-hidden="true"><defs><linearGradient id={'trust-'+kind} x1="20" y1="0" x2="240" y2="110" gradientUnits="userSpaceOnUse"><stop stopColor="#60b050" stopOpacity=".12"/><stop offset=".52" stopColor="#9edbcf" stopOpacity=".8"/><stop offset="1" stopColor="#70c060" stopOpacity=".2"/></linearGradient></defs><g stroke={'url(#trust-'+kind+')'} strokeWidth="1"><path d="M0 55H70M190 55H260M30 20H65Q85 20 85 40M30 90H65Q85 90 85 70M175 40Q175 20 195 20H230M175 70Q175 90 195 90H230"/>{kind==='local'?<><rect x="90" y="22" width="80" height="66" rx="12"/><path d="M104 40H156M104 53H145M104 66H138"/><circle cx="154" cy="70" r="3" fill="#70c060"/></>:kind==='models'?<><path d="M85 55L130 20L175 55L130 90Z"/><path d="M85 55H175M130 20V90"/>{[[85,55],[130,20],[175,55],[130,90]].map(([x,y])=><circle key={x+'-'+y} cx={x} cy={y} r="7" fill="var(--surface)"/>)}<circle cx="130" cy="55" r="13"/></>:kind==='execution'?<><path d="M82 72L110 45L136 60L176 27" strokeWidth="2"/>{[[82,72],[110,45],[136,60],[176,27]].map(([x,y])=><circle key={x} cx={x} cy={y} r="5" fill="var(--surface)"/>)}<path d="M82 88H178M82 20V88" opacity=".3"/></>:<><path d="M130 16L163 29V53C163 74 147 85 130 94C113 85 97 74 97 53V29Z"/><rect x="115" y="46" width="30" height="24" rx="5"/><path d="M121 46V38A9 9 0 0 1 139 38V46M130 55V61"/></>}</g><path className="trust-trace" d="M0 55H70M190 55H260" stroke="#a2e4d9" strokeWidth="2" strokeDasharray="12 240"/><circle cx="20" cy="55" r="2" fill="#70c060"/><circle cx="240" cy="55" r="2" fill="#70c060"/></svg>}

export function SectionBackdrop({variant}){
 const ref=useRef(),enabled=useLandingMotion(),visible=useVisible(ref);
 const closing=variant==='closing',height=closing?320:800;
 const paths=closing?[
  'M-80 285C240 285 260 30 620 52S1080 330 1510 65',
  'M-80 310C280 300 280 55 650 77S1110 350 1510 95',
  'M-80 335C310 325 310 80 680 102S1140 370 1510 125',
  'M-80 40C310 10 410 290 850 265S1240 30 1510 25'
 ]:[
  'M-80 660C170 650 140 145 470 125S990 220 1510 40',
  'M-80 695C200 685 170 180 500 160S1020 255 1510 75',
  'M-80 730C230 720 200 215 530 195S1050 290 1510 110',
  'M-80 130C250 90 260 630 710 680S1190 450 1510 650',
  'M-80 165C280 125 290 665 740 715S1220 485 1510 685'
 ];
 return <div ref={ref} className={'section-backdrop '+variant} data-playing={enabled&&visible} aria-hidden="true"><svg viewBox={'0 0 1440 '+height} preserveAspectRatio="none" fill="none"><defs><linearGradient id={'section-wire-'+variant} x1="0" y1="0" x2="1440" y2={height} gradientUnits="userSpaceOnUse"><stop stopColor="#407040" stopOpacity=".06"/><stop offset=".3" stopColor="#70c060" stopOpacity=".5"/><stop offset=".7" stopColor="#a2e4d9" stopOpacity=".24"/><stop offset="1" stopColor="#60b050" stopOpacity=".06"/></linearGradient></defs>{paths.map((d,i)=><g key={d} style={{'--signal-time':`${14+i*3}s`,'--signal-delay':`${-i*4-2}s`}}><path d={d} stroke={'url(#section-wire-'+variant+')'} strokeWidth="1" vectorEffect="non-scaling-stroke"/><path className="section-signal halo" d={d} pathLength="1000"/><path className="section-signal" d={d} pathLength="1000"/></g>)}</svg></div>
}

export function ClosingTypewriter(){const ref=useRef(),enabled=useLandingMotion(),visible=useVisible(ref),[count,setCount]=useState(0);const text='Give your next idea a place to work.';useEffect(()=>{if(!enabled||!visible)return;let timer;const tick=()=>{if(document.hidden){timer=setTimeout(tick,300);return}setCount(n=>n<text.length?n+1:0)};timer=setTimeout(tick,count===text.length?5000:65);return()=>clearTimeout(timer)},[count,enabled,visible]);return <h2 ref={ref} className="closing-typewriter"><span className="landing-sr-only">{text}</span><span className="closing-type-space" aria-hidden="true">Give your next idea a place to <em>work.</em></span><span className="closing-type-ink" aria-hidden="true">{text.slice(0,Math.min(enabled?count:text.length,30))}<em>{text.slice(30,enabled?count:text.length)}</em><i className={enabled?'type-caret':'type-caret still'}/></span></h2>}
