import React,{useEffect,useRef} from 'react';
export default function LandingMotion(){
 const host=useRef();
 useEffect(()=>{const node=host.current;let gone=false,epoch=0,dispose=()=>{};const media=matchMedia('(prefers-reduced-motion: reduce)');
 const start=async()=>{const ticket=++epoch;dispose();dispose=()=>{};if(media.matches){node.dataset.motion='static';return}const T=await import('three');if(gone||media.matches||ticket!==epoch)return;let renderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:false,powerPreference:'low-power'})}catch{node.dataset.motion='fallback';return}node.appendChild(renderer.domElement);node.dataset.motion='playing';renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));const scene=new T.Scene(),camera=new T.PerspectiveCamera(42,1,.1,80);camera.position.z=15;const group=new T.Group();scene.add(group);const resources=[],signals=[];
 const pixels=new Uint8Array(32*32*4);for(let y=0;y<32;y++)for(let x=0;x<32;x++){const d=Math.hypot((x-15.5)/15.5,(y-15.5)/15.5),k=(y*32+x)*4;pixels[k]=pixels[k+1]=pixels[k+2]=255;pixels[k+3]=Math.round(Math.pow(Math.max(0,1-d),3)*255)}const glow=new T.DataTexture(pixels,32,32);glow.needsUpdate=true;resources.push(glow);
 const orbitPoint=(j,a,target)=>{const r=5.5+j*.47;return target.set(Math.cos(a)*r,Math.sin(a)*r*.53,Math.sin(a*2+j*.13)*.8)};

 for(let j=0;j<9;j++){const points=[];for(let i=0;i<=200;i++){const a=i/200*Math.PI*2;const r=5.5+j*.47;points.push(new T.Vector3(Math.cos(a)*r,Math.sin(a)*r*.53,Math.sin(a*2+j*.13)*.8))}const geometry=new T.BufferGeometry().setFromPoints(points),material=new T.LineBasicMaterial({color:j%3===0?0x70c060:0x407040,transparent:true,opacity:j%3===0?.28:.12});resources.push(geometry,material);const line=new T.Line(geometry,material);line.rotation.z=j*.085;group.add(line);
 const lane=new T.Group();lane.rotation.z=line.rotation.z;group.add(lane);
 for(let k=0;k<2;k++){const mat=new T.SpriteMaterial({map:glow,color:k===0?0xa6eee2:0x91d67a,transparent:true,opacity:.95,blending:T.AdditiveBlending,depthWrite:false});resources.push(mat);const bulb=new T.Sprite(mat);bulb.scale.setScalar(.36);lane.add(bulb);const tailGeometry=new T.BufferGeometry(),tailPositions=new Float32Array(48),colors=[];for(let n=0;n<16;n++){const fade=Math.pow(1-n/16,2);colors.push(.4*fade,.85*fade,.73*fade)}tailGeometry.setAttribute('position',new T.BufferAttribute(tailPositions,3));tailGeometry.setAttribute('color',new T.Float32BufferAttribute(colors,3));const tailMaterial=new T.LineBasicMaterial({vertexColors:true,transparent:true,opacity:.65,blending:T.AdditiveBlending,depthWrite:false});resources.push(tailGeometry,tailMaterial);const tail=new T.Line(tailGeometry,tailMaterial);tail.frustumCulled=false;lane.add(tail);signals.push({j,k,bulb,tailGeometry,tailPositions});}
 }
 const geometry=new T.BufferGeometry(),positions=[];for(let i=0;i<75;i++){const a=i*2.399963;positions.push(Math.cos(a)*(5+i%9*.5),Math.sin(a)*(3+i%7*.4),Math.sin(i)*2)}geometry.setAttribute('position',new T.Float32BufferAttribute(positions,3));const material=new T.PointsMaterial({color:0x9daa9d,size:.025,transparent:true,opacity:.36});resources.push(geometry,material);group.add(new T.Points(geometry,material));group.rotation.z=-.18;
 let frame=0,last=0,visible=true,time=0;const resize=()=>{const r=node.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(node);resize();const draw=now=>{frame=requestAnimationFrame(draw);if(now-last<1000/30)return;time+=Math.min(now-last,50)/1000;last=now;group.rotation.y=Math.sin(time*.055)*.16;group.rotation.z=-.18+Math.sin(time*.04)*.12;group.position.y=Math.sin(time*.08)*.25;for(const signal of signals){const a=time*(.13+signal.j*.009)+signal.j*.73+signal.k*Math.PI;orbitPoint(signal.j,a,signal.bulb.position);signal.bulb.material.opacity=.7+Math.sin(time*1.4+signal.j)*.22;for(let n=0;n<16;n++){const r=5.5+signal.j*.47,b=a-n*.018;signal.tailPositions[n*3]=Math.cos(b)*r;signal.tailPositions[n*3+1]=Math.sin(b)*r*.53;signal.tailPositions[n*3+2]=Math.sin(b*2+signal.j*.13)*.8}signal.tailGeometry.attributes.position.needsUpdate=true;}renderer.render(scene,camera)};const sync=()=>{cancelAnimationFrame(frame);if(!gone&&visible&&!document.hidden){last=performance.now();frame=requestAnimationFrame(draw)}};const intersection=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;sync()});intersection.observe(node);document.addEventListener('visibilitychange',sync);const lost=e=>{e.preventDefault();visible=false;sync();node.dataset.motion='fallback'};renderer.domElement.addEventListener('webglcontextlost',lost);sync();dispose=()=>{cancelAnimationFrame(frame);observer.disconnect();intersection.disconnect();document.removeEventListener('visibilitychange',sync);renderer.domElement.removeEventListener('webglcontextlost',lost);resources.forEach(r=>r.dispose());renderer.dispose();renderer.domElement.remove()};};start().catch(()=>{node.dataset.motion='fallback'});media.addEventListener('change',start);return()=>{gone=true;media.removeEventListener('change',start);dispose()};
 },[]);
 return <div ref={host} className="cinematic-orbits" aria-hidden="true"/>
}
export function SectionMotion(){useEffect(()=>{let gone=false,context,observer;const media=matchMedia('(prefers-reduced-motion: reduce)');if(media.matches)return;const stop=()=>{if(media.matches){observer?.disconnect();context?.revert()}};media.addEventListener('change',stop);import('gsap').then(({gsap})=>{if(gone)return;context=gsap.context(()=>{observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){gsap.from(entry.target,{y:18,duration:.8,ease:'power2.out',clearProps:'transform'});observer.unobserve(entry.target)}})},{threshold:.12});document.querySelectorAll('.capability-strip>a,.how-section,.trust-strip>div,.closing-cta').forEach(n=>observer.observe(n))})});return()=>{gone=true;media.removeEventListener('change',stop);observer?.disconnect();context?.revert()}},[]);return null}
