import React,{useState} from 'react';
import {Panel,Button,Icon,Status} from './ui';
import {api} from './api';
export default function ResourceInspector({view,resource,state,showPanel,showTabs,refresh,act,onClose}){
 const[tab,setTab]=useState('Inspector');const project=resource?.kind==='project'?state.projects.find(p=>p.id===resource.id):state.projects.find(p=>p.id===resource?.projectId);const data=resource?.kind==='project'?project:resource?.kind==='workflow'?state.workflows.find(w=>w.id===resource.id):resource;
 const relatedRuns=state.runs.filter(r=>r.projectId===project?.id);
 return <aside className="inspector" aria-label={view+' inspector'}><button className="inspector-close" aria-label="Close inspector" onClick={onClose}><Icon name="X"/></button>{showTabs&&<div className="tabs">{['Inspector','Logs','Resources'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>}{showPanel&&<div className="inspector-body">{!data?<Panel title={view}><Icon name={view}/><p>Select an item to inspect its details and related work.</p></Panel>:tab==='Inspector'?<><Panel title={data.name||data.title}><p>{data.description||data.kind}</p>{data.status&&<Status value={data.status}/>}<dl><dt>ID</dt><dd className="resource-id">{data.id}</dd>{data.createdAt&&<><dt>Created</dt><dd>{new Date(data.createdAt).toLocaleString()}</dd></>}{project&&<><dt>Project</dt><dd>{project.name}</dd></>}</dl>{resource.kind==='project'&&<form key={project.id+project.updatedAt} onSubmit={e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));act(async()=>{await api('/projects/'+project.id,values,'PATCH');await refresh()})}}><label className="field"><span>Project goal</span><textarea name="goal" rows={4} maxLength={2000} defaultValue={project.goal||''}/></label><label className="field"><span>Decisions and working notes</span><textarea name="decisions" rows={7} maxLength={8000} defaultValue={project.decisions||''}/></label><Button type="submit">Save project context</Button></form>}{data.kind==='artifact'&&<a className="button" href={'/api/artifacts/'+data.id}><Icon name="Download"/>Download artifact</a>}{data.compatibility&&<p>{data.compatibility.state} · {data.compatibility.reason}</p>}</Panel>{resource.kind==='project'&&<Panel title="Persistent work"><dl><dt>Runs</dt><dd>{relatedRuns.length}</dd><dt>Artifacts</dt><dd>{state.artifacts.filter(a=>a.projectId===project.id).length}</dd><dt>Files</dt><dd>{state.files.filter(f=>f.projectId===project.id).length}</dd><dt>Workflows</dt><dd>{(state.workflows||[]).filter(w=>w.projectId===project.id).length}</dd></dl></Panel>}</>:tab==='Logs'?<Panel title="Execution history">{relatedRuns.length?relatedRuns.slice(-12).reverse().map(r=><details key={r.id}><summary>{r.prompt.slice(0,50)} · {r.status}</summary><p>{r.error||'Execution '+r.status}</p><a href={'/api/runs/'+r.id+'/export'}>Download audit record</a></details>):<p>No associated executions.</p>}</Panel>:<Panel title="Project resources">{state.files.filter(f=>f.projectId===project?.id).map(f=><a className="file-row" key={f.id} href={'/api/files/'+f.id}>{f.name}</a>)}{state.artifacts.filter(f=>f.projectId===project?.id).map(f=><a className="file-row" key={f.id} href={'/api/artifacts/'+f.id}>{f.name}</a>)}{!project&&<p>No project associated with this selection.</p>}</Panel>}</div>}</aside>
}

