import Preview from './LandingPreview';
import {HeroTypewriter,PipelineDemo,TrustArt,SectionBackdrop,ClosingTypewriter} from './LandingDetails';
import LandingMotion,{SectionMotion} from './LandingMotion';
import React,{useState,useEffect} from 'react';
import App from './App';
import {Logo,Icon} from './ui';
import ThemeControl from './ThemeControl';
import {workspaceViews,workspacePath} from './routes';

const capabilities=[['Projects','Organize work, ideas, and outcomes in one place.'],['Runs','Give Astra a goal. Follow every execution.'],['Artifacts','Keep, explore, and iterate on every output.'],['Integrations','Connect models, tools, and skills to fit your work.']];
function Brand(){return <a className="site-brand" href="/"><Logo/><span>Astra Workspace</span></a>}

function Header({early=false}){const[open,setOpen]=useState(false);return <header className="site-header"><Brand/><button className="site-menu" aria-expanded={open} aria-label="Toggle page navigation" onClick={()=>setOpen(!open)}><Icon name="Menu"/></button><nav className={open?'open':''} aria-label="Public navigation"><a href="/#product">Product</a><a href={early?'/#capabilities':'/#capabilities'}>{early?'Use cases':'Features'}</a><a href={early?'#trust':'/workspace/integrations'}>{early?'Security':'Integrations'}</a><a href={early?'#faq':'/#how-it-works'}>{early?'FAQ':'How it works'}</a></nav><div className="site-account"><ThemeControl/><a href="/workspace">Open workspace</a>{!early&&<a className="site-button accent" href="/early-access">Get started <Icon name="ArrowRight"/></a>}</div></header>}
function Trust(){return <section className="trust-strip" id="trust"><div><TrustArt kind="local"/><span><strong>Your workspace stays local</strong><small>Projects, history, and artifacts persist on this device.</small></span></div><div><TrustArt kind="models"/><span><strong>Multi-model by design</strong><small>Independent Responses API and Codex execution adapters.</small></span></div><div><TrustArt kind="execution"/><span><strong>Visible execution</strong><small>Inspect requests, approvals, errors, and results.</small></span></div><div><TrustArt kind="security"/><span><strong>Development without secrets</strong><small>A local simulator. No real keys or model charges.</small></span></div></section>}
function Footer(){return <footer className="site-footer"><Brand/><span>Give Astra a place to work.</span><a href="/#trust">Privacy & control</a><a href="/early-access">Early access</a><a href="/workspace">Workspace <Icon name="ArrowUpRight"/></a></footer>}
function Landing(){return <><Header/><LandingMotion/><SectionMotion/><main><section className="landing-hero" id="product"><h1>Give Astra a place to <em>work.</em></h1><HeroTypewriter/><div className="hero-actions"><a className="site-button premium" href="/early-access">Get started <Icon name="ArrowRight"/></a><a className="site-button" href="/workspace"><Icon name="Play"/> Explore workspace</a></div><div className="hero-sequence">Build <span/> Automate <span/> Orchestrate <span/> Accelerate</div><Preview/></section><section className="capability-strip" id="capabilities">{capabilities.map(([name,copy])=><a href={workspacePath(name)} key={name}><span className="capability-icon"><Icon name={name} size={27}/></span><div><h2>{name==='Runs'?'Run tasks':name==='Artifacts'?'Manage artifacts':name==='Integrations'?'Connect everything':name}</h2><p>{copy}</p></div></a>)}</section><section className="how-section" id="how-it-works"><SectionBackdrop variant="workflow"/><p className="eyebrow">ONE PERSISTENT ENVIRONMENT</p><h2>From intention to a result you can return to.</h2><PipelineDemo/><p>Choose a model, give Astra a task, inspect its work, and keep the outcome with your project. Start locally with the simulator; configure live providers in production when you are ready.</p></section><Trust/><section className="closing-cta"><SectionBackdrop variant="closing"/><ClosingTypewriter/><a href="/workspace" className="site-button accent">Open workspace <Icon name="ArrowRight"/></a></section></main><Footer/></>}
const faqs=[['When will early access start?','This build is a local development preview. A public launch date has not been announced.'],['Is there a cost to join the waitlist?','This preview records your interest locally and does not charge you. A hosted waitlist is not connected.'],['How is my data handled?','This form stays in this browser’s local storage. It is not sent to Astra or any provider. You can remove the saved entry after submitting.'],['Can I invite my team?','Team accounts and invitations are planned. This build is a single-user local workspace.'],['Which providers and models are supported?','The runtime supports Responses API, OpenAI-compatible chat providers, and a Codex app-server adapter. Development uses a deterministic simulator. Live providers need separate production configuration.'],['Will there be enterprise plans?','Enterprise plans have not been announced. Current security controls and supported features are documented in the workspace; no enterprise certification is claimed.']];
function EarlyAccess(){const[saved,setSaved]=useState(()=>{try{return JSON.parse(localStorage.getItem('astra-early-access')||'null')}catch{return null}}),[error,setError]=useState('');function submit(e){e.preventDefault();const data=new FormData(e.currentTarget);try{const entry={email:String(data.get('email')).trim(),size:data.get('size'),interests:data.getAll('interest'),createdAt:new Date().toISOString()};localStorage.setItem('astra-early-access',JSON.stringify(entry));setSaved(entry);setError('')}catch{setError('This browser could not save your interest. Enable local storage and try again.')}}return <><Header early/><main><section className="early-hero"><div className="early-copy"><p className="eyebrow">EARLY ACCESS <span/></p><h1>Join the Astra Workspace <em>early access.</em></h1><p>A unified workspace to build, run, and orchestrate AI-powered work. Be among the first to explore what’s next.</p>{saved?<div className="early-form" role="status"><Icon name="Check" size={32}/><h2>Your interest is saved on this device.</h2><p>No email was sent and no account was created. Your local workspace is ready to explore.</p><a className="site-button accent" href="/workspace">Open workspace <Icon name="ArrowRight"/></a><button className="text-button" onClick={()=>{localStorage.removeItem('astra-early-access');setSaved(null)}}>Remove my saved entry</button></div>:<form className="early-form" onSubmit={submit}><div className="early-fields"><label>Work email <span>*</span><input type="email" autoComplete="email" name="email" placeholder="you@company.com" required maxLength={254}/></label><label>Company size <span>*</span><select name="size" required defaultValue=""><option value="" disabled>Select size</option>{['Just me','2–10','11–50','51–200','201+'].map(x=><option key={x}>{x}</option>)}</select></label></div><fieldset><legend>What are you most interested in? (Select all that apply)</legend><div className="interest-grid">{['Projects','Runs','Artifacts','Skills','Workflows','Integrations'].map(x=><label key={x}><input type="checkbox" name="interest" value={x}/><Icon name={x}/>{x}</label>)}</div></fieldset><button className="site-button premium" type="submit">Save early-access interest <Icon name="ArrowRight"/></button><p className="form-note"><Icon name="Lock" size={14}/> Local preview only. Nothing is sent from this form.</p>{error&&<p role="alert">{error}</p>}</form>}</div><div className="early-preview"><Preview compact/><p>One workspace. Infinite possibilities.</p></div></section><Trust/><section className="faq-section" id="faq"><div><p className="eyebrow">FAQ</p><h2>Frequently<br/> asked <em>questions.</em></h2></div><div className="faq-grid">{faqs.map(([q,a])=><details key={q}><summary>{q}<Icon name="ChevronDown" size={16}/></summary><p>{a}</p></details>)}</div></section></main><Footer/></>}
export default function Site(){const path=location.pathname;const hash=location.hash.slice(1);if(path==='/'&&workspaceViews.includes(hash)){history.replaceState({},'',workspacePath(hash));return <App/>}if(path==='/workspace'||path.startsWith('/workspace/'))return <App/>;return <div className={'public-site '+(path==='/'?'landing-mode':'')}>{path==='/'?<Landing/>:path==='/early-access'||path==='/signup'?<EarlyAccess/>:<><Header/><main className="missing-page"><h1>This page isn’t here.</h1><a className="site-button" href="/">Return home</a></main><Footer/></>}</div>}


