import React,{useState,useEffect} from 'react';
import {api} from './api';
import {Button,Field} from './ui';
export function Skills({state,projectId,refresh,onInspect}){
 const [catalog,setCatalog]=useState(null),[detail,setDetail]=useState(null),[filter,setFilter]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[project,setProject]=useState(projectId||''),[source,setSource]=useState('flowchart LR\nRequest[Request] --> Delegate[Delegate]\nDelegate --> Execute[Execute]\nExecute --> Result[Save result]'),[diagram,setDiagram]=useState(null);
 const action=async fn=>{setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{onInspect?.(detail)},[detail]);
 const load=async()=>setCatalog(await api('/skills'));
 useEffect(()=>{let alive=true;api('/skills').then(d=>alive&&setCatalog(d)).catch(e=>alive&&setError(e.message));return()=>{alive=false}},[]);
 return <section className="management"><div className="section-heading"><div><h1>Skills</h1><p>Canonical definitions from Skill Hub. Astra owns activation and execution.</p></div><Button disabled={busy} onClick={()=>action(async()=>{setCatalog(await api('/skills/refresh',{}));setDetail(null)})}>Refresh registry</Button></div>
 {error&&<p role="alert" className="form-error">{error}</p>}
 {catalog&&<><p className="hint">{catalog.source.count} native packages · revision {catalog.source.revision.slice(0,12)} · read-only source</p><Field label="Search skills"><input value={filter} onChange={e=>setFilter(e.target.value)}/></Field><div className="catalog-layout"><div className="skill-list">{catalog.skills.filter(s=>(s.name+' '+s.description).toLowerCase().includes(filter.toLowerCase())).map(s=><button className="skill-row" key={s.id} aria-pressed={s.id===detail?.id} disabled={busy} onClick={()=>action(async()=>{setDetail(await api('/skills/'+s.id));setDiagram(null)})}><strong>{s.name}</strong><small>{s.description}</small><span className="badge-state">{s.compatibility.state}</span></button>)}</div>
 <div className="skill-detail">{!detail?<p className="muted">Select a skill to inspect its definition, qualification and runtime requirements.</p>:<><h2>{detail.name}</h2><p>{detail.description}</p><p className="compatibility">{detail.compatibility.state} · {detail.compatibility.reason}</p><dl><dt>Native status</dt><dd>{detail.status}</dd><dt>Runtime binding</dt><dd>{detail.compatibility.binding||'Not qualified'}</dd><dt>Model</dt><dd>{detail.compatibility.binding==='archify-local'?'Not required':state.settings.model}</dd><dt>Version</dt><dd>{detail.version}</dd><dt>Content hash</dt><dd>{detail.content_hash.slice(0,20)}</dd></dl><div className="skill-actions"><Button disabled={busy||['BLOCKED','UNSUPPORTED'].includes(detail.compatibility.state)} onClick={()=>action(async()=>{setDetail(await api('/skills/'+detail.id+'/activation',{enabled:!detail.compatibility.enabled}));await load()})}>{detail.compatibility.enabled?'Disable':'Enable'}</Button><a className="button" href={'https://github.com/Fallenproud/skill-hub-registry/blob/'+catalog.source.revision+'/'+detail.package_path+'/SKILL.md'} target="_blank" rel="noreferrer">Canonical source</a></div>
 <details><summary>Inspect SKILL.md</summary><pre>{detail.markdown}</pre></details><details><summary>Inspect metadata and permissions</summary><pre>{JSON.stringify(detail.metadata,null,2)}</pre></details>
 {detail.compatibility.binding==='archify-local'&&<><h3>Invoke Archify</h3><p className="hint">Local, deterministic rendering. Supports acyclic Mermaid flowcharts with 2–12 nodes, decisions and labeled arrows. Unsupported syntax fails explicitly. No model or API key is used.</p><Field label="Diagram project"><select value={project} onChange={e=>setProject(e.target.value)}><option value="">Select project</option>{state.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Mermaid source"><textarea rows={7} value={source} onChange={e=>setSource(e.target.value)}/></Field><Button disabled={busy||!detail.compatibility.enabled||!project} onClick={()=>action(async()=>{setDiagram(await api('/skills/'+detail.id+'/invoke',{projectId:project,source}));await refresh()})}>{busy?'Working…':'Invoke skill'}</Button></>}
 {diagram&&<><p className="success">Archify validation passed. Receipt saved; browser/perceptual review is separate.</p><div className="runtime-links"><a href={'/api/diagrams/'+diagram.id+'/content'} target="_blank" rel="noreferrer">Open diagram</a><a href={'/api/diagrams/'+diagram.id+'/receipt'} target="_blank" rel="noreferrer">Validation receipt</a></div><iframe title="Archify diagram" className="diagram-frame" sandbox="allow-scripts allow-downloads" src={'/api/diagrams/'+diagram.id+'/content'}/></>}
 </>}</div></div></>}
 <h3>Saved diagrams</h3>{(state.diagrams||[]).map(d=><div className="file-row" key={d.id}><span>{d.title}</span><a href={'/api/diagrams/'+d.id+'/content'} target="_blank" rel="noreferrer">Open</a><a href={'/api/diagrams/'+d.id+'/receipt'} target="_blank" rel="noreferrer">Receipt</a></div>)}
 </section>
}
