import React from 'react';import{Home,Workflow,Sparkles,File,Folder,SquarePlay,FileText,Puzzle,Settings,Plus,Paperclip,Globe,Play,ArrowUpRight,ArrowRight,Sun,Moon,Database,ChevronDown,Activity,Clock,Link,ShieldCheck,X,Menu,Lock,Square,Download,Check,Trash2,RefreshCw,Brain,Terminal,Search,MessageSquare}from'lucide-react';
export const icons={Home,Skills:Sparkles,Workflows:Workflow,Workspace:File,Projects:Folder,Runs:SquarePlay,Artifacts:FileText,Integrations:Puzzle,Settings,Plus,Paperclip,Globe,Play,ArrowUpRight,ArrowRight,Sun,Moon,Database,ChevronDown,Activity,Clock,Link,ShieldCheck,X,Menu,Lock,Square,Download,Check,Trash2,RefreshCw,Brain,Terminal,Search,MessageSquare};
export function Icon({name,size=18,...p}){const C=icons[name]||File;return <C size={size} strokeWidth={1.6} {...p}/>}
export function Logo({large=false}){return <span className={'logo '+(large?'large':'')} aria-label="Astra"><img src="/astra-folded-a.svg" alt="" width="40" height="40"/></span>}
export function Button({children,icon,primary=false,...p}){return <button className={primary?'button primary':'button'} {...p}>{icon&&<Icon name={icon}/>} {children}</button>}
export function Panel({title,children,action}){return <section className="panel"><div className="panel-title">{title}{action}</div>{children}</section>}
export function Empty({title,children,icon='Activity'}){return <div className="empty"><Icon name={icon} size={28}/><h3>{title}</h3><p>{children}</p></div>}
export function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
export function Modal({title,children,onClose}){const ref=React.useRef();React.useEffect(()=>{const previous=document.activeElement;ref.current?.querySelector('input,button,select,textarea')?.focus();return()=>previous?.focus()},[]);const keys=e=>{if(e.key==='Escape'){e.preventDefault();onClose?.()}if(e.key==='Tab'){const nodes=[...ref.current.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')].filter(n=>n.offsetParent!==null);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose?.()}><section ref={ref} onKeyDown={keys} className="modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2>{onClose&&<button aria-label="Close" onClick={onClose}><Icon name="X"/></button>}</header>{children}</section></div>}
export function Status({value}){return <span className={'status '+value}><i/>{String(value||'ready').replaceAll('_',' ')}</span>}
export const number=n=>Number(n||0).toLocaleString();
export const time=s=>s?new Date(s).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'';
