import React,{useEffect,useState} from 'react';import {api} from './api';import {Icon,Button,Status} from './ui';
const names={timeline:'Activity',files:'Files',context:'Context',artifacts:'Artifacts',workflow:'Workflow'};
export default function WorkspaceSurfaces({state,run,act,refresh}){
 const layout=state.workspaceLayouts?.find(l=>l.conversationId===run?.conversationId),[tab,setTab]=useState('timeline'),[closed,setClosed]=useState(false),[events,setEvents]=useState([]),[file,setFile]=useState(null),[template,setTemplate]=useState(null);
 useEffect(()=>{setTab('timeline');setClosed(false);setFile(null);setTemplate(null)},[run?.id]);
 useEffect(()=>{if(!run||closed)return;let live=true;const load=()=>api('/runs/'+run.id+'/events').then(e=>live&&setEvents(e)).catch(()=>{});load();const t=setInterval(load,1500);return()=>{live=false;clearInterval(t)}},[run?.id,closed]);
 if(!layout)return null;const panels=layout.panels.filter(p=>names[p]);const active=panels.includes(tab)?tab:panels[0],workflow=state.workflows?.find(w=>w.id===run.workflowId),files=state.files.filter(f=>f.projectId===run.projectId),artifacts=state.artifacts.filter(a=>a.projectId===run.projectId);
 return <section className="workspace-surfaces" aria-label="Composed workspace"><header><span><Icon name="Workspace"/> {layout.purpose}</span><Button type="button" aria-expanded={!closed} onClick={()=>setClosed(!closed)}>{closed?'Show workspace views':'Hide workspace views'}</Button></header>{!closed&&<><div className="surface-nav" role="tablist" aria-label="Workspace views">{panels.map(p=><button role="tab" id={'view-'+p} aria-controls="workspace-view" aria-selected={active===p} key={p} onClick={()=>{setTab(p);setFile(null)}}>{names[p]}</button>)}{state.workspaceTemplates?.length>0&&<select aria-label="Saved workspace layout" value="" onChange={e=>act(async()=>{await api('/workspace-layouts/'+layout.id+'/template',{templateId:e.target.value});await refresh()})}><option value="">Apply saved layout</option>{state.workspaceTemplates.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select>}<Button type="button" onClick={()=>act(async()=>{const t=await api('/workspace-layouts/'+layout.id+'/promote',{});setTemplate(t);await refresh()})}>Save layout template</Button></div><div role="tabpanel" id="workspace-view" aria-labelledby={'view-'+active} className="workspace-view">{active==='timeline'&&<><p className="hint">{layout.reason}</p>{events.slice(-6).map(e=><details key={e.id}><summary><time>{new Date(e.createdAt).toLocaleTimeString()}</time> {e.type.replaceAll('_',' ')}</summary><pre>{JSON.stringify(e.data,null,2)}</pre></details>)}</>}{active==='context'&&<><h3>Context used for this run</h3><p>{run.contextSnapshot?.goal||run.contextSnapshot?.description||'No project goal was set for this run.'}</p><p>{run.contextSnapshot?.decisions}</p><small>{run.model} · {run.reasoning} reasoning · {run.contextLimit} token context limit</small></>}{active==='files'&&<>{files.length?files.map(f=><button className="file-row" key={f.id} onClick={()=>act(async()=>{const response=await fetch('/api/files/'+f.id);if(!response.ok)throw Error('File could not be loaded');setFile({name:f.name,content:await response.text()})})}><Icon name="Artifacts"/>{f.name}<small>{f.size} bytes</small></button>):<p className="hint">Attach text or code files from the composer to inspect them here.</p>}{file&&<details open><summary>{file.name}</summary><pre>{file.content}</pre></details>}</>}{active==='artifacts'&&<>{artifacts.map(a=><a className="file-row" key={a.id} href={'/api/artifacts/'+a.id}><Icon name="Download"/>{a.name}<small>{a.size} bytes</small></a>)}{!artifacts.length&&<p>No artifacts have been produced.</p>}</>}{active==='workflow'&&<>{workflow?<ol>{workflow.steps.map(s=><li key={s.id}>{s.agentName} <Status value={s.status}/></li>)}</ol>:<p>Workflow record is not available.</p>}</>}</div>{template&&<p role="status" className="hint">Layout template saved. Read-only views carry no new execution permissions.</p>}</>}</section>
}
