import React,{useState} from 'react';
import {api} from './api';
import {Button,Field,Status} from './ui';
export function Workflows({state,projectId,refresh,selectRun,onInspect}){
 const [name,setName]=useState('Review and deliver'),[project,setProject]=useState(projectId||''),[steps,setSteps]=useState([{agentId:'',prompt:''}]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[diagram,setDiagram]=useState(null),[agentName,setAgentName]=useState(''),[instructions,setInstructions]=useState('');
 const action=async fn=>{setBusy(true);setError('');try{await fn();await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const update=(i,key,value)=>setSteps(s=>s.map((x,n)=>n===i?{...x,[key]:value}:x));
 return <section className="management"><div className="section-heading"><div><h1>Workflows</h1><p>Delegate bounded steps to agents. Inspect every child run and approval.</p></div></div>{error&&<p role="alert" className="form-error">{error}</p>}
 <div className="template-options">{(state.workflowTemplates||[]).map(t=><Button key={t.id} disabled={busy} onClick={()=>{setName(t.name);setSteps(t.steps.map(s=>({...s})))}}>Load {t.name}</Button>)}</div><details><summary>Create a runtime agent</summary><form onSubmit={e=>{e.preventDefault();action(async()=>{await api('/agents',{name:agentName,instructions});setAgentName('');setInstructions('')})}}><Field label="Agent name"><input required maxLength={60} value={agentName} onChange={e=>setAgentName(e.target.value)}/></Field><Field label="Agent instructions"><textarea required rows={4} maxLength={10000} value={instructions} onChange={e=>setInstructions(e.target.value)}/></Field><Button disabled={busy} type="submit">Create agent</Button></form></details>
 <form onSubmit={e=>{e.preventDefault();action(()=>api('/workflows',{name,projectId:project,steps}))}}><div className="form-grid"><Field label="Workflow name"><input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Workflow project"><select required value={project} onChange={e=>setProject(e.target.value)}><option value="">Select project</option>{state.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field></div>
 {steps.map((s,i)=><div className="workflow-step" key={i}><strong>Step {i+1}</strong><Field label={'Step '+(i+1)+' agent'}><select required value={s.agentId} onChange={e=>update(i,'agentId',e.target.value)}><option value="">Select agent</option>{state.agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label={'Step '+(i+1)+' task'}><textarea required maxLength={10000} value={s.prompt} onChange={e=>update(i,'prompt',e.target.value)}/></Field>{steps.length>1&&<Button type="button" onClick={()=>setSteps(s=>s.filter((_,n)=>n!==i))}>Remove step</Button>}</div>)}
 <div className="skill-actions"><Button type="button" disabled={steps.length>=8||busy} onClick={()=>setSteps([...steps,{agentId:'',prompt:''}])}>Add delegated step</Button><Button type="button" disabled={busy||!state.agents.length} onClick={()=>action(()=>api('/workflow-templates',{name,steps}))}>Save reusable template</Button><Button type="submit" disabled={busy||!state.agents.length}>Run workflow</Button></div><p className="hint">Steps execute sequentially with separate conversation scopes. Prior text and artifact references become the next step’s context. Approval, cancellation and failure stop progression. Development runs are simulated.</p></form>
 {(state.workflows||[]).slice().reverse().map(w=><article className="workflow-run" key={w.id}><h3>{w.name} <Status value={w.status}/></h3><Button onClick={()=>onInspect(w)}>Inspect workflow</Button>{w.simulated&&<p className="hint">Simulated agents · real orchestration and persistence</p>}{w.error&&<p role="alert">{w.error}</p>}<ol>{w.steps.map(s=><li key={s.id}>{s.agentName} · {s.status} {s.runId&&<Button onClick={()=>{const r=state.runs.find(r=>r.id===s.runId);if(r)selectRun(r)}}>Open run</Button>}</li>)}</ol><div className="skill-actions">{!['completed','cancelled','failed','interrupted'].includes(w.status)&&<Button disabled={busy} onClick={()=>action(()=>api('/workflows/'+w.id+'/cancel',{}))}>Cancel workflow</Button>}<Button disabled={busy} onClick={()=>{setName(w.name);setProject(w.projectId);setSteps(w.steps.map(({agentId,prompt})=>({agentId,prompt})))}}>Reuse steps</Button><Button disabled={busy} onClick={()=>action(async()=>setDiagram(await api('/workflows/'+w.id+'/diagram',{})))}>Visualize workflow</Button></div></article>)}
 {diagram&&<><h3>{diagram.title}</h3><a href={'/api/diagrams/'+diagram.id+'/receipt'} target="_blank" rel="noreferrer">Archify validation receipt</a><iframe className="diagram-frame" title="Workflow diagram" sandbox="allow-scripts allow-downloads" src={'/api/diagrams/'+diagram.id+'/content'}/></>}
 </section>
}
